# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 07:24
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    replaces = [('pomodoro', '0001_initial'), ('pomodoro', '0002_favorite'), ('pomodoro', '0003_auto_20151106_1256'), ('pomodoro', '0004_auto_20160101_0429'), ('pomodoro', '0005_favorite_icon')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=timezone.now, verbose_name='start time')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('category', models.CharField(blank=True, max_length=32, verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('icon', models.ImageField(blank=True, upload_to='pomodoro/favorites')),
            ],
        ),
    ]
