# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_auto_20151106_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='category',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
