# Generated by Django 1.10.5 on 2017-03-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
