# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_auto_20160101_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='icon',
            field=models.ImageField(blank=True, upload_to='pomodoro/favorites'),
        ),
    ]
