# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:33
from __future__ import unicode_literals

from django.db import migrations, models

from pomodoro import util


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0004_favorite_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-count',)},
        ),
        migrations.AlterField(
            model_name='favorite',
            name='icon',
            field=models.ImageField(blank=True, upload_to=util._upload_to_path),
        ),
    ]
