# Generated by Django 2.2.5 on 2019-10-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("pomodoro", "0005_auto_20171212_1133")]

    operations = [
        migrations.AddField(
            model_name="favorite", name="url", field=models.URLField(blank=True)
        ),
        migrations.AddField(
            model_name="pomodoro", name="memo", field=models.TextField(blank=True)
        ),
        migrations.AddField(
            model_name="pomodoro",
            name="url",
            field=models.URLField(blank=True, help_text="Optional link"),
        ),
    ]
