# Generated by Django 2.2.9 on 2020-05-03 09:26

from django.db import migrations, models


def default_active(apps, schema_editor):
    Project = apps.get_model("pomodoro", "Project")
    Project.objects.all().update(active=True)


class Migration(migrations.Migration):

    dependencies = [
        ("pomodoro", "0008_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(default_active, migrations.RunPython.noop),
    ]
