# Generated by Django 2.2.9 on 2020-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0009_project_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
