# Generated by Django 2.2.13 on 2021-03-06 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0010_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='duration'),
        ),
        migrations.CreateModel(
            name='FavoritePomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('favorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.Favorite')),
                ('pomodoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pomodoro.Pomodoro')),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='pomodoro_set',
            field=models.ManyToManyField(through='pomodoro.FavoritePomodoro', to='pomodoro.Pomodoro'),
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ('-pomodoro_set__count',)},
        ),
    ]
