# Generated by Django 3.2.8 on 2022-10-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoro', '0012_increase_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
