# Generated by Django 3.2.16 on 2024-03-12 10:23

from django.db import migrations

import pomodoro.fields
import pomodoro.util


def prefix_color(apps, schema_editor):
    # For our forward migration, we want to find every project color where we
    # need to prefix with a # character
    Project = apps.get_model("pomodoro", "Project")
    for p in Project.objects.exclude(color__startswith="#"):
        p.color = f"#{p.color}"
        p.save()


def strip_color(apps, schema_editor):
    # For our reverse migration, we want to find every project where we need to
    # strip a # character from the color
    Project = apps.get_model("pomodoro", "Project")
    for p in Project.objects.filter(color__startswith="#"):
        p.color = p.color.strip("#")
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("pomodoro", "0013_delete_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="color",
            field=pomodoro.fields.ColorField(),
        ),
        migrations.RunPython(prefix_color, strip_color),
    ]
